[theme]
primaryColor = "#1677ff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#262626"
font = "sans serif"

[server]
maxUploadSize = 10
enableXsrfProtection = false

[browser]
gatherUsageStats = false
